version: '3'
services:
  php:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

#  mysql:
#    image: mysql:8.0
#    environment:
#      - MYSQL_ROOT_PASSWORD=root

